# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Aggregator
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A theme based on Webjeda.


#baseurl: "/cards" # the subpath of your site, e.g. /blog
#url: "https://elmundoesimperfecto.com" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: fernand0 based on webjeda's work

copyright:
   name: fernand0 / webjeda
   link: 'https://elmundoesimperfecto.com/'

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus: yes
# disqus-shortname: some-user

#social
facebook: http://facebook.com/
quora: http://quora.com/
twitter: http://twitter.com/
github: http://github.com/
email: your@email.com

# #facebook like box
# fb-like-box: yes
# fb-app-id: 123456789012345
# fb-page-url: https://www.facebook.com/somePage/
# fb-page-title: someTitle

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins:
  - jekyll-seo-tag
  #  - jekyll-paginate

